### ISSUE TITLE
Use SomeAsyncException to detect asynchronous exceptions

### ISSUE THREAD

**Issue by snoyberg** [singpolyma/unexceptionalio#9]
Since base 4.7, there is a new exception "superclass" `SomeAsyncException` which all asynchronous exceptions are supposed to extend (via the extensible exceptions mechanism). Adding support for this to `syncIO` would do two things:
- Add support for user-defined async exceptions
- Make for a more universal definition of async exceptions

Looking at the list of exceptions currently marked as asynchronous, it looks like many of them (like `ArithException`) are miscategorized, which can lead to incorrect behavior, e.g.:

``` haskell
#!/usr/bin/env stack
-- stack --resolver lts-6.3 runghc --package unexceptionalio

import Control.Exception
import UnexceptionalIO

main :: IO ()
main = syncIO (evaluate (1 `div` 0)) >>= print
```

Results in a runtime exception:

```
async.hs: divide by zero
```

By contrast, with safe-exceptions:

``` haskell
import Control.Exception (evaluate)
import Control.Exception.Safe

main :: IO ()
main = tryAny (evaluate (1 `div` 0)) >>= print
```

Results in printing a `Left` value as expected:

```
Left divide by zero
```

Pinging @Gabriel439 as well, since this affects `errors`.

**Comment by singpolyma** [comment]
Using the superclass sounds like a good idea for the relevant exceptions, but we'll still need seperate rethrows as you say for things like ArithException that are programmer errors and not runtime errors.

**Comment by snoyberg** [comment]
I'm not sure I follow, what behavior are you looking for here? To me, the current behavior of `UnexceptionalIO` is buggy, since a synchronously generated exception is escaping `syncIO`, seemingly in contradiction to its primary purpose.

**Comment by singpolyma** [comment]
It does seem like at some point the docs on syncIO got simplified too much and now imply I should only miss "asynchronous exceptions". When in fact it is meant to miss anything that is not really an exception that just happens to use GHC's exception mechanism (ErrorCall, ArithException, etc)

**Comment by chreekat** [comment]
Hm.. I feel like `ArithException` is certainly both synchronous and exceptional.

**Comment by Gabriel439** [comment]
I agree with Michael and think having `syncIO` ignore exactly `SomeAsyncException` is a good default

**Comment by singpolyma** [comment]
I will work on this soon. Though I'm still unsure about changing the semantics to exclude ArithException... maybe a new helper that does async-only and one that also catches the programming error "exceptions"

**Comment by singpolyma** [comment]
I have pushed some work on this (and a test suite) and it seems that `SomeAsyncException` is not a superclass for all kinds of things thrown by the runtime, such as `BlockedIndefinitelyOnSTM`, `BlockedIndefinitelyOnMVar`, `Deadlock`, `NonTermination` as well as of course the previously-mentioned "programmer error" cases (error calls, pattern match failures, etc), and a third class that I'd totally forgotten to mention: `ExitCode`

Anyway, the code on `master` now uses `SomeAsyncException` to cover the cases it covers, which is a good change.

**Comment by snoyberg** [comment]
The definitions in base are correct. Things like Deadlock should be treated as synchronous exceptions. My recent blog post on this topic covers these details

https://www.fpcomplete.com/blog/2018/04/async-exception-handling-haskell

I consider it dangerous to have a custom definition of asynchronous exceptions floating around the ecosystem, especially as the basis for a highly recommended library like errors.

**Comment by singpolyma** [comment]
I wouldn't characterize it as a "custom definition of async" since the library explicitly says "non-error and asynchronous" (notwithstanding the previous documentation error, fixed in master) and there's now a test suite which clearly shows the three different categories.

I'm not sure in what case, a developer would want to exclude async exceptions *only" but still catch other exceptions thrown by the runtime, bad pattern matches, etc

I can of course see cases where a developer wants to handle *everything* (resource handling with bracket or a daemon that logs errors first instead of crashing right away) but that's a different use case

**Comment by singpolyma** [comment]
Due to https://github.com/Gabriel439/Haskell-Errors-Library/pull/53 I am going to remove `syncIO` from this library (since it only existed to mirror the API from `errors` and then introduce a second package for the transformers variant of UIO.

**Comment by singpolyma** [comment]
https://hackage.haskell.org/package/unexceptionalio-trans and https://hackage.haskell.org/package/unexceptionalio both uploaded and updated to new major version to reflect this.

I was going to add more/better documentation to prevent confusion in the future, but realised when looking at it that the main issue was imprecision of the types (just saying `SomeException` everywhere and meaning different things) so the exception classification is now explicit at the type/instance level instead of being a magic list of rethrows you have to read the source to find.  I have also added wrappers around `bracket` and `forkFinally` to demonstrate the most common cases where you still want to deal with `PseudoException`s
